### ISSUE TITLE
Unable to make!!

### ISSUE THREAD

**Issue by Dharm94** [rhgndf/ms912x#1]
dharm@dharm-IdeaPad:~/Desktop/ms912x$ sudo ./insmod.sh 
[sudo] password for dharm: 
make -C /lib/modules/5.15.0-48-generic/build M=/home/dharm/Desktop/ms912x clean
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-48-generic'
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-48-generic'
rm -f /home/dharm/Desktop/ms912x/Module.symvers /home/dharm/Desktop/ms912x/*.ur-safe
make CHECK="/usr/bin/sparse" -C /lib/modules/5.15.0-48-generic/build M=/home/dharm/Desktop/ms912x modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-48-generic'
  CC [M]  /home/dharm/Desktop/ms912x/ms912x_registers.o
  CC [M]  /home/dharm/Desktop/ms912x/ms912x_connector.o
  CC [M]  /home/dharm/Desktop/ms912x/ms912x_transfer.o
  CC [M]  /home/dharm/Desktop/ms912x/ms912x_drv.o
  LD [M]  /home/dharm/Desktop/ms912x/ms912x.o
  MODPOST /home/dharm/Desktop/ms912x/Module.symvers
  CC [M]  /home/dharm/Desktop/ms912x/ms912x.mod.o
  LD [M]  /home/dharm/Desktop/ms912x/ms912x.ko
  BTF [M] /home/dharm/Desktop/ms912x/ms912x.ko
Skipping BTF generation for /home/dharm/Desktop/ms912x/ms912x.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-48-generic'
rmmod: ERROR: Module ms912x is not currently loaded

**Comment by rhgndf** [comment]
The error can be safely ignored.

**Comment by Dharm94** [comment]
Can you list your kernal !!!!!!!

Bcoz only once i was able to see flickered screen on my second monitor

Now it's not showing

Btw i'm using dual boot 22.04,

**Comment by Dharm94** [comment]
Hey ! When it worked at that time output was like :

![Screenshot from 2022-10-03 20-25-37](https://user-images.githubusercontent.com/58878437/193626236-96d68710-3998-459f-a409-9545280b2be5.png)



Now when i run make all -j [The last line is not coming and even nothing is working now.]

![Screenshot from 2022-10-03 21-26-31](https://user-images.githubusercontent.com/58878437/193626358-7bdcfece-5da7-42cc-b1df-1ce7478b3c8d.png)

**Comment by rhgndf** [comment]
I use kernel 5.17. It works on 5.15 for me, not sure what's wrong. Try a reboot?

**Comment by Dharm94** [comment]
Worked on kernel 5.15.0.47 & ****.48 !!! But still FPS is very low <,,

But thank you So SO So much ;)
