### ISSUE TITLE
This does not appear in sway

### ISSUE THREAD

**Issue by thenightterorx** [rhgndf/ms912x#9]
My adapter shows up in xorg (granted, I've only tried i3) and even in other wayland implementations like gnome, but there is nothing about it when I do swaymsg -t get_outputs. I'm probably just missing something here though so any guidance is appreciated.

**Comment by rhgndf** [comment]
First thing to check is if it supports DRM hotplug? Some environments do not have good support for display devices coming up and being removed while it is running.

**Comment by thenightterorx** [comment]
After messing around with it, I ended up doing 3 things, some of which might not really be necessary. The --unsupported-gpu flag, export WLR_DRM_NO_MODIFIERS=1, and export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1.
